# render.yaml - Render deployment configuration

services:
  - type: web
    name: UEMOA-banking-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./API
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    healthCheckPath: /health
    disk:
      name: model-storage
      mountPath: /app/models
      # sizeGB: 1
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1